[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "upapasta"
version = "0.1.0"
authors = [
  { name="Franzopl", email="author@example.com" },
]
description = "A script to upload folders to Usenet with RAR, PAR2, and nyuu."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.scripts]
upapasta = "upapasta.main:main"
